// FrontEnd/src/lib/components/Header.svelte
<script>
  let mobileMenuOpen = false;

  function toggleMobileMenu() {
    mobileMenuOpen = !mobileMenuOpen;
  }
</script>

<header class="header-area style-1">
  <div class="header-logo">
    <a rel="external" href="/">
      <img alt="BidNest Header Logo" src="/assets/images/bg/header-logo.png" />
    </a>
  </div>

  <div class="main-menu" class:open={mobileMenuOpen}>
    <div
      class="mobile-logo-area d-lg-none d-flex justify-content-between align-items-center"
    >
      <div class="mobile-logo-wrap">
        <a rel="external" href="/">
          <img
            alt="BidNest Header Logo"
            src="/assets/images/bg/header-logo.png"
          />
        </a>
      </div>
      <button
        type="button"
        class="menu-close-btn"
        on:click={toggleMobileMenu}
        aria-label="Close menu"
      >
        <i class="bi bi-x-lg"></i>
      </button>
    </div>

    <ul class="menu-list">
      <li><a rel="external" href="/" class="drop-down">Home</a></li>
      <li><a rel="external" href="/about">About Us</a></li>
      <li><a rel="external" href="/how-works">How It Works</a></li>
      <li><a rel="external" href="/live-auction">Browse Product</a></li>
      <li class="menu-item-has-children">
        <a rel="external" href="/news">News</a>
        <i class="bx bx-plus dropdown-icon"></i>
        <ul class="submenu">
          <li><a rel="external" href="/blog">Blog</a></li>
          <li><a rel="external" href="/blog-details">Blog Details</a></li>
        </ul>
      </li>
      <li class="menu-item-has-children">
        <a rel="external" href="#" class="drop-down">Pages</a>
        <i class="bx bx-plus dropdown-icon"></i>
        <ul class="submenu">
          <li><a rel="external" href="/auction-details">Auction Details</a></li>
          <li><a rel="external" href="/faq">Faq</a></li>
          <li><a rel="external" href="/dashboard">Dashboard</a></li>
          <li><a rel="external" href="/login">Login</a></li>
          <li><a rel="external" href="/signup">Sign Up</a></li>
          <li><a rel="external" href="/404">404</a></li>
        </ul>
      </li>
      <li><a rel="external" href="/contact">Contact</a></li>
    </ul>

    <div class="d-lg-none d-block">
      <form class="mobile-menu-form mb-5">
        <div class="input-with-btn d-flex flex-column">
          <input type="text" placeholder="Search here..." />
          <button type="submit" class="eg-btn btn--primary btn--sm"
            >Search</button
          >
        </div>
      </form>

      <div class="hotline two">
        <div class="hotline-info">
          <span>Click To Call</span>
          <h6><a href="tel:+3472748816">+347-274-8816</a></h6>
        </div>
      </div>
    </div>
  </div>

  <div class="nav-right d-flex align-items-center">
    <div class="hotline d-xxl-flex d-none">
      <div class="hotline-icon">
        <img alt="" src="/assets/images/icons/header-phone.svg" />
      </div>
      <div class="hotline-info">
        <span>Click To Call</span>
        <h6><a href="tel:+3472748816">+347-274-8816</a></h6>
      </div>
    </div>

    <div class="search-btn">
      <i class="bi bi-search"></i>
    </div>

    <div class="eg-btn btn--primary header-btn">
      <a rel="external" href="/login">My Account</a>
    </div>

    <button
      type="button"
      class="mobile-menu-btn d-lg-none d-block"
      on:click={toggleMobileMenu}
      aria-label="Open mobile menu"
    >
      <i class="bx bx-menu"></i>
    </button>
  </div>
</header>

<style>
  /* Add your styles here */
  .main-menu.open {
    display: block;
  }
</style>

// FrontEnd/src/components/Header.jsx
import React, { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';

const Header = () => {
    // const [menuItems, setMenuItems] = useState([]);

    // useEffect(() => {
    //     // Fetch menu items from an API or a local JSON file
    //     const fetchMenuItems = async () => {
    //         try {
    //             const response = await fetch('/api/menu-items'); // Replace with your API endpoint
    //             const data = await response.json();
    //             setMenuItems(data);
    //         } catch (error) {
    //             console.error('Error fetching menu items:', error);
    //         }
    //     };

    //     fetchMenuItems();
    // }, []);

    const menuItems = [
        {
            "id": 1,
            "name": "Home",
            "link": "/",
            "submenu": [
                { "id": 1, "name": "Home 1", "link": "/home1" },
                { "id": 2, "name": "Home 2", "link": "/home2" },
                { "id": 3, "name": "Home 3", "link": "/home3" }
            ]
        },
        {
            "id": 2,
            "name": "About Us",
            "link": "/about"
        },
        {
            "id": 3,
            "name": "How It Works",
            "link": "/how-works"
        },
        {
            "id": 4,
            "name": "Browse Product",
            "link": "/live-auction"
        },
        {
            "id": 5,
            "name": "News",
            "link": "/news",
            "submenu": [
                { "id": 1, "name": "Blog", "link": "/blog" },
                { "id": 2, "name": "Blog Details", "link": "/blog-details" }
            ]
        },
        {
            "id": 6,
            "name": "Pages",
            "link": "/pages",
            "submenu": [
                { "id": 1, "name": "Auction Details", "link": "/auction-details" },
                { "id": 2, "name": "FAQ", "link": "/faq" },
                { "id": 3, "name": "Dashboard", "link": "/dashboard" },
                { "id": 4, "name": "Login", "link": "/login" },
                { "id": 5, "name": "SignUp", "link": "/signup" },
                { "id": 6, "name": "404", "link": "/404" }
            ]
        },
        {
            "id": 7,
            "name": "Contact",
            "link": "/contact"
        }
    ];

    return (
        <header className="header-area style-1">
            <div className="header-logo">
                <Link to="/"><img alt="image" src="assets/images/bg/header-logo.png" /></Link>
            </div>
            <div className="main-menu">
                <div className="mobile-logo-area d-lg-none d-flex justify-content-between align-items-center">
                    <div className="mobile-logo-wrap">
                        <Link to="/"><img alt="image" src="assets/images/bg/header-logo.png" /></Link>
                    </div>
                    <div className="menu-close-btn">
                        <i className="bi bi-x-lg" />
                    </div>
                </div>
                <ul className="menu-list">
                    {menuItems.map((item) => (
                        <li key={item.id} className={item.submenu ? "menu-item-has-children" : ""}>
                            <Link to={item.link} className={item.submenu ? "drop-down" : ""}>{item.name}</Link>
                            {item.submenu && <i className="bx bx-plus dropdown-icon" />}
                            {item.submenu && (
                                <ul className="submenu">
                                    {item.submenu.map((subItem) => (
                                        <li key={subItem.id}>
                                            <Link to={subItem.link}>{subItem.name}</Link>
                                        </li>
                                    ))}
                                </ul>
                            )}
                        </li>
                    ))}
                    <li><Link to="/contact">Contact</Link></li>
                </ul>
                <div className="d-lg-none d-block">
                    <form className="mobile-menu-form mb-5">
                        <div className="input-with-btn d-flex flex-column">
                            <input type="text" placeholder="Search here..." />
                            <button type="submit" className="eg-btn btn--primary btn--sm">Search</button>
                        </div>
                    </form>
                    <div className="hotline two">
                        <div className="hotline-info">
                            <span>Click To Call</span>
                            <h6><a href="tel:347-274-8816">+347-274-8816</a></h6>
                        </div>
                    </div>
                </div>
            </div>
            <div className="nav-right d-flex align-items-center">
                <div className="hotline d-xxl-flex d-none">
                    <div className="hotline-icon">
                        <img alt="image" src="assets/images/icons/header-phone.svg" />
                    </div>
                    <div className="hotline-info">
                        <span>Click To Call</span>
                        <h6><a href="tel:347-274-8816">+347-274-8816</a></h6>
                    </div>
                </div>
                <div className="search-btn">
                    <i className="bi bi-search" />
                </div>
                <div className="eg-btn btn--primary header-btn">
                    <Link to="/dashboard">My Account</Link>
                </div>
                <div className="mobile-menu-btn d-lg-none d-block">
                    <i className="bx bx-menu" />
                </div>
            </div>
        </header>
    );
}

export default Header;
